# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'd:\py_project\DJ_folder_main1\test.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
import sys

sys.path.append("./")
from main_meng_2 import main
from video_gen import extract_faces_from_videos


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(383, 289)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout.setObjectName("gridLayout")
        self.frame_4 = QtWidgets.QFrame(self.centralwidget)
        self.frame_4.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_4.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_4.setObjectName("frame_4")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.frame_4)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.label_2 = QtWidgets.QLabel(self.frame_4)
        self.label_2.setScaledContents(True)
        self.label_2.setObjectName("label_2")
        self.verticalLayout_2.addWidget(self.label_2)
        self.label_3 = QtWidgets.QLabel(self.frame_4)
        self.label_3.setText("")
        self.label_3.setScaledContents(True)
        self.label_3.setObjectName("label_3")
        self.verticalLayout_2.addWidget(self.label_3)
        self.gridLayout.addWidget(self.frame_4, 1, 1, 1, 1)
        self.frame = QtWidgets.QFrame(self.centralwidget)
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.frame)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.label_5 = QtWidgets.QLabel(self.frame)
        self.label_5.setScaledContents(True)
        self.label_5.setObjectName("label_5")
        self.gridLayout_2.addWidget(self.label_5, 0, 0, 1, 1)
        self.lineEdit = QtWidgets.QLineEdit(self.frame)
        self.lineEdit.setObjectName("lineEdit")
        self.gridLayout_2.addWidget(self.lineEdit, 1, 0, 1, 1)
        self.pushButton = QtWidgets.QPushButton(self.frame)
        self.pushButton.setObjectName("pushButton")
        self.gridLayout_2.addWidget(self.pushButton, 2, 0, 1, 1)
        self.textBrowser = QtWidgets.QTextBrowser(self.frame)
        self.textBrowser.setObjectName("textBrowser")
        self.gridLayout_2.addWidget(self.textBrowser, 3, 0, 1, 1)
        self.gridLayout.addWidget(self.frame, 0, 0, 1, 1)
        self.frame_2 = QtWidgets.QFrame(self.centralwidget)
        self.frame_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_2.setObjectName("frame_2")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.frame_2)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.lineEdit_2 = QtWidgets.QLineEdit(self.frame_2)
        self.lineEdit_2.setObjectName("lineEdit_2")
        self.gridLayout_3.addWidget(self.lineEdit_2, 1, 0, 1, 1)
        self.pushButton_2 = QtWidgets.QPushButton(self.frame_2)
        self.pushButton_2.setObjectName("pushButton_2")
        self.gridLayout_3.addWidget(self.pushButton_2, 2, 0, 1, 1)
        self.label_4 = QtWidgets.QLabel(self.frame_2)
        self.label_4.setScaledContents(True)
        self.label_4.setObjectName("label_4")
        self.gridLayout_3.addWidget(self.label_4, 0, 0, 1, 1)
        self.textBrowser_2 = QtWidgets.QTextBrowser(self.frame_2)
        self.textBrowser_2.setObjectName("textBrowser_2")
        self.gridLayout_3.addWidget(self.textBrowser_2, 3, 0, 1, 1)
        self.gridLayout.addWidget(self.frame_2, 0, 1, 1, 1)
        self.frame_3 = QtWidgets.QFrame(self.centralwidget)
        self.frame_3.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_3.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_3.setObjectName("frame_3")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.frame_3)
        self.verticalLayout.setObjectName("verticalLayout")
        self.label = QtWidgets.QLabel(self.frame_3)
        self.label.setScaledContents(True)
        self.label.setObjectName("label")
        self.verticalLayout.addWidget(self.label)
        self.comboBox = QtWidgets.QComboBox(self.frame_3)
        self.comboBox.setObjectName("comboBox")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.verticalLayout.addWidget(self.comboBox)
        self.textBrowser_3 = QtWidgets.QTextBrowser(self.frame_3)
        self.textBrowser_3.setObjectName("textBrowser_3")
        self.verticalLayout.addWidget(self.textBrowser_3)
        self.gridLayout.addWidget(self.frame_3, 0, 2, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

        self.pushButton.clicked.connect(self.start_video_capture)
        self.pushButton_2.clicked.connect(self.start_face_selection)
        self.comboBox.currentIndexChanged.connect(self.update_label_text)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(
            _translate("MainWindow", "人脸质量增强的重复数据筛选系统")
        )
        self.label_2.setText(
            _translate("MainWindow", "处理过程中未响应属于正常现象哟!")
        )
        self.label_5.setText(_translate("MainWindow", "视频人脸数据生成"))
        self.pushButton.setText(_translate("MainWindow", "Start"))
        self.pushButton_2.setText(_translate("MainWindow", "Start"))
        self.label_4.setText(_translate("MainWindow", "重复人脸数据筛选"))
        self.label.setText(_translate("MainWindow", "保留n张人脸图片"))
        self.comboBox.setItemText(0, _translate("MainWindow", " "))
        self.comboBox.setItemText(1, _translate("MainWindow", "2"))
        self.comboBox.setItemText(2, _translate("MainWindow", "3"))
        self.comboBox.setItemText(3, _translate("MainWindow", "4"))
        self.comboBox.setItemText(4, _translate("MainWindow", "5"))

    video_capture_count = 0
    face_selection_count = 0
    selected_num = 2
    # flag_selected_num = False
    # flag_video_gen = False

    # 视频截取
    def start_video_capture(self):
        self.video_path = self.lineEdit.text()
        if self.video_path:  # 检查输入框是否为空
            self.textBrowser.append(f"视频地址: {self.video_path}")
            # TODO: 编写实际的视频截取功能
            self.textBrowser.append("正在截取视频中的人脸，请稍等...")
            extract_faces_from_videos(self.video_path)
            self.video_capture_count += 1
            self.textBrowser.append(f"第 {self.video_capture_count} 次视频截取完成")
        else:
            QtWidgets.QMessageBox.warning(None, "错误", "输入为空，请重新输入")
        self.label_3.setText("视频截取完成！")

    # 人脸挑选
    def start_face_selection(self):
        self.face_path = self.lineEdit_2.text()
        # self.textBrowser_2.append("挑选人脸过程中未响应属于正常现象")
        if self.face_path:  # 检查输入框是否为空
            self.textBrowser_2.append(f"人脸图片地址: {self.face_path}")
            # TODO: 编写实际的人脸挑选功能
            self.textBrowser_2.append("正在挑选人脸，请稍等...,未响应属于正常现象")
            # self.textBrowser_2.append(f"将保留 {self.selected_num} 张图片")
            main(self.face_path, self.selected_num)
            self.face_selection_count += 1
            self.textBrowser_2.append(f"第 {self.face_selection_count} 次人脸挑选完成")
        else:
            QtWidgets.QMessageBox.warning(None, "错误", "输入为空，请重新输入")
        self.label_3.setText("人脸挑选完成！")

    # 输出结果
    def update_label_text(self):
        # TODO: 这个变量用来传参
        self.n_images = self.comboBox.currentText()
        self.textBrowser_3.append(f"将保留 {self.n_images} 张图片")
        # TODO: 括号里这个参数填入实际的完成状态
        self.selected_num = int(self.n_images)
        self.label_3.setText(self.n_images)
